<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCju9yzf\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCju9yzf/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCju9yzf.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCju9yzf\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCju9yzf\appProdProjectContainer([
    'container.build_hash' => 'Cju9yzf',
    'container.build_id' => '028af610',
    'container.build_time' => 1568800947,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCju9yzf');
