<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUzqfsxi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUzqfsxi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUzqfsxi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUzqfsxi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUzqfsxi\appDevDebugProjectContainer([
    'container.build_hash' => 'Uzqfsxi',
    'container.build_id' => 'bf92fe5f',
    'container.build_time' => 1568801914,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUzqfsxi');
